### ISSUE TITLE
Thanks page after submitting the form which is not payment option not looking proper.

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#115]
After submitting the form without any payment option still shows the transaction id and amount content on Thanks page.
Check here-
![image](https://user-images.githubusercontent.com/77260614/132631238-03cb7997-bfa7-496c-ba3c-1850e207325b.png)

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
Not fixed still showing the same page
![image](https://user-images.githubusercontent.com/77260614/132734692-7e5a568f-a53d-4b8f-8fb5-a7e7a5714365.png)

**Comment by mJawed** [comment]
it is done, please retest it after deployment

**Comment by charan-singh05** [comment]
Issue fix verified.
