### ISSUE TITLE
When added the new organization then not immeadiately showing in the dropdown list of the organization.[Organization-workflow]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#76]
1. Login and add a new organization
2. Then check the organization list.
3. Now check the organization workflow list dropdown on the header.

Expected result-when a new organization is added then it will show in the dropdown list of the organization immediately.

Actual result-When added a new organization then that organization was not added to the list immediately. When the user logout and again login then it will show in the dropdown list.

**Comment by hunny-metagauss** [comment]
fixed

**Comment by Bhagyashrimane** [comment]
Working fine.

**Comment by Bhagyashrimane** [comment]
1. Still facing the same issue. Organization added in the list but not in organization workflow dropdown.
2. When creating a new organization filled all data in the form and click on the save page redirects to plans. Then trying to select the plan not redirecting on the billing page it is redirecting back to the General organization form page. That's why showing validation message with organization name field like "Workspace name already exists".

**Comment by hunny-metagauss** [comment]
done

**Comment by Bhagyashrimane** [comment]
Working fine.
